### ISSUE TITLE
In main.py...

### ISSUE THREAD

**Issue by kimkyeonghun** [addb-swstarlab/RocksDB-data-generation#1]
In your annotation in main.py, you write "수정필요" from line 24 to 47.
I want to know the problem that codes have.

**Comment by huijunjin** [comment]
The code has no problem, we wrote the annotation because the code indicates the specific values of RocksDB parameters. 
We hired a RocksDB expert to shrink the range of each parameter to a certain degree to make sure none of those parameters exceed their reasonable range so that no error occurs when generating RocksDB data. 
Besides, if the other people want to use our model, he should change those parameters to his own database-oriented parameters rather than the parameters of RocksDB

**Comment by kimkyeonghun** [comment]
Thank you
